<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-27T10:46:17Z" name="Default suite" finished-at="2022-11-27T10:46:39Z" duration-ms="21888">
    <groups>
    </groups>
    <test started-at="2022-11-27T10:46:17Z" name="Default test" finished-at="2022-11-27T10:46:39Z" duration-ms="21888">
      <class name="testcases.SimplilearnLoginTest">
        <test-method is-config="true" signature="DataSetUp()[pri:0, instance:testcases.SimplilearnLoginTest@4681c175]" started-at="2022-11-27T10:46:17Z" name="DataSetUp" finished-at="2022-11-27T10:46:18Z" duration-ms="1331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataSetUp -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.SimplilearnLoginTest@4681c175]" started-at="2022-11-27T10:46:18Z" name="SetUp" finished-at="2022-11-27T10:46:25Z" duration-ms="7006" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.SimplilearnLoginTest.Test1()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Test1()[pri:0, instance:testcases.SimplilearnLoginTest@4681c175]" started-at="2022-11-27T10:46:25Z" name="Test1" finished-at="2022-11-27T10:46:37Z" duration-ms="11750" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The email or password you have entered is invalid] but found [The email or password you have entered is invalid.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The email or password you have entered is invalid] but found [The email or password you have entered is invalid.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testcases.SimplilearnLoginTest.Test1(SimplilearnLoginTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.SimplilearnLoginTest@4681c175]" started-at="2022-11-27T10:46:37Z" name="TearDown" finished-at="2022-11-27T10:46:38Z" duration-ms="493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="DataClean()[pri:0, instance:testcases.SimplilearnLoginTest@4681c175]" started-at="2022-11-27T10:46:38Z" name="DataClean" finished-at="2022-11-27T10:46:39Z" duration-ms="576" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataClean -->
      </class> <!-- testcases.SimplilearnLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
